Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  Name: go-blog-app
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: Root@1234
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: geekr
  Issuer: go-blog-app
  Expire: 7200 #s
Email:
  Host: smtp-mail.outlook.com
  Port: 587
  UserName: yaojinbu@outlook.com
  Password: xxxxxx
  IsSSL: true
  From: yaojinbu@outlook.com
