info:
  contact: {}
  description: 基于 Go 构建简单博客系统
  termsOfService: https://github.com/geekr-dev/go-blog-app
  title: Blog App
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
        "500":
          description: 服务错误
          schema:
            type: Object
      summary: 获取标签列表
    post:
      parameters:
      - description: 标签名称
        in: body
        maxLength: 100
        minLength: 3
        name: name
        required: true
        schema:
          type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: integer
      - description: 作者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
        "500":
          description: 服务错误
          schema:
            type: Object
      summary: 新增标签
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
        "500":
          description: 服务错误
          schema:
            type: Object
      summary: 删除标签
    put:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标签名称
        in: body
        maxLength: 100
        minLength: 3
        name: name
        schema:
          type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: integer
      - description: 编辑
        in: body
        maxLength: 100
        minLength: 3
        name: updated_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
        "500":
          description: 服务错误
          schema:
            type: Object
      summary: 修改标签
swagger: "2.0"
